### ISSUE TITLE
Can this be used in a script?

### ISSUE THREAD

**Issue by rowisahub** [samyakbambole/ironer#1]
Like can I call this in my code, cause to make a discord bot template would be beneficial but not really useful if I can't use it my code. And if you can, can you update the README

**Comment by samyakbambole** [comment]
No, This cannot be used as a script as this npm package is supposed to be used globally. 
You can Create a Discord Bot Template using the command - `ironer discord-bot <directory name>`

**Comment by samyakbambole** [comment]
If you enter this command, Ironer clones the github repo - https://github.com/samyakbambole/discord-bot-template

**Comment by samyakbambole** [comment]
If you know how to make an npm package to be used as a script, Feel free to edit the code!

**Comment by samyakbambole** [comment]
Im Closing this issue for now but if there are updates reagrding the issue, the issue will be reopened
